"""Map canonical data to Food Excel schema."""

from __future__ import annotations

from typing import Any, Dict

from domain.canonical import CanonicalRow


def canonical_to_food_row(c: CanonicalRow) -> Dict[str, Any]:
    """Convert a CanonicalRow to Food Excel row format.
    
    Article Number is left as None - will be generated by article_number logic.
    Price/Unit is extracted from canonical (when extract_price=True) or None.
    """
    return {
        "Article Number": None,  # Generated separately
        "EAN code unit": c.get("ean"),
        "Product Description": c.get("product_description"),
        "Content": c.get("content"),
        "Languages": c.get("languages"),
        "Piece per case": c.get("piece_per_case"),
        "Case per pallet": c.get("case_per_pallet"),
        "Pieces per pallet": c.get("pieces_per_pallet"),
        "BBD": c.get("bbd"),
        "Availability/Cartons": c.get("availability_cartons"),
        "Availability/Pieces": c.get("availability_pieces"),
        "Availability/Pallets": c.get("availability_pallets"),
        "Price/Unit (Euro)": c.get("price_unit_eur"),  # ✅ Extract from canonical
    }